# Generated by Django 5.2.10 on 2026-01-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='ФИО на русском')),
                ('name_en', models.CharField(max_length=255, verbose_name='ФИО на английском')),
                ('name_kg', models.CharField(max_length=255, verbose_name='ФИО на кыргызском')),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(upload_to='acadmic_council_photos/')),
            ],
            options={
                'verbose_name': 'Член академического совета',
                'verbose_name_plural': 'Члены академического совета',
            },
        ),
    ]
