# Generated by Django 6.0.1 on 2026-01-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_council', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccouncil',
            name='role',
        ),
        migrations.AddField(
            model_name='academiccouncil',
            name='role_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='role(en)'),
        ),
        migrations.AddField(
            model_name='academiccouncil',
            name='role_kg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='role(kg)'),
        ),
        migrations.AddField(
            model_name='academiccouncil',
            name='role_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='role(ru)'),
        ),
    ]
