# Generated by Django 5.2.10 on 2026-01-30 14:28

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/', verbose_name='Логотип')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название (EN)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('name_kg', models.CharField(max_length=255, verbose_name='Название (KG)')),
                ('description_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description (RU)')),
                ('description_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description (EN)')),
                ('description_kg', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description (KG)')),
                ('coord1', models.CharField(blank=True, max_length=55, null=True, verbose_name='координаты ширины(LAT)')),
                ('coord2', models.CharField(blank=True, max_length=55, null=True, verbose_name='координаты долготы(LMG)')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['id'],
            },
        ),
    ]
