# Generated by Django 5.2.8 on 2025-11-27 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="Название (EN)"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Название (RU)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=255, verbose_name="Название (KG)"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["title_ru"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_recommended",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Отображать в разделе рекомендованных новостей",
                        verbose_name="Рекомендуемая",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="Заголовок (EN)"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Заголовок (RU)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=255, verbose_name="Заголовок (KG)"),
                ),
                (
                    "short_description_en",
                    models.TextField(blank=True, verbose_name="Краткое описание (EN)"),
                ),
                (
                    "short_description_ru",
                    models.TextField(blank=True, verbose_name="Краткое описание (RU)"),
                ),
                (
                    "short_description_kg",
                    models.TextField(blank=True, verbose_name="Краткое описание (KG)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Описание (EN)"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Описание (RU)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Описание (KG)"),
                ),
                (
                    "fulltext_en",
                    models.TextField(blank=True, verbose_name="Полный текст (EN)"),
                ),
                (
                    "fulltext_ru",
                    models.TextField(blank=True, verbose_name="Полный текст (RU)"),
                ),
                (
                    "fulltext_kg",
                    models.TextField(blank=True, verbose_name="Полный текст (KG)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Рекомендуемый размер: 1200x630px",
                        null=True,
                        upload_to="news/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news",
                        to="presscentre.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="news_created_idx"),
                    models.Index(
                        fields=["is_recommended", "-created_at"],
                        name="news_recommended_idx",
                    ),
                    models.Index(
                        fields=["category", "-created_at"], name="news_category_idx"
                    ),
                ],
            },
        ),
    ]
