# Generated by Django 5.2.8 on 2025-11-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("presscentre", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="fulltext_en",
        ),
        migrations.RemoveField(
            model_name="news",
            name="fulltext_kg",
        ),
        migrations.RemoveField(
            model_name="news",
            name="fulltext_ru",
        ),
    ]
