# Generated by Django 5.2.8 on 2025-11-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "presscentre",
            "0002_remove_news_fulltext_en_remove_news_fulltext_kg_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="publieshed_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Дата публикации"
            ),
        ),
    ]
