# Generated by Django 5.2.8 on 2025-11-30 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("presscentre", "0003_news_publieshed_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="publieshed_at",
            new_name="published_at",
        ),
    ]
