# Generated by Django 5.2.8 on 2025-11-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presscentre", "0004_rename_publieshed_at_news_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="published_at",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Дата публикации"
            ),
        ),
    ]
