# Generated by Django 5.2.8 on 2025-12-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presscentre", "0005_alter_news_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_banner",
            field=models.BooleanField(
                default=False,
                help_text="Отображать новость в виде баннера на главной странице",
                verbose_name="Баннер",
            ),
        ),
    ]
