# Generated by Django 5.2.8 on 2025-12-14 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presscentre", "0006_news_is_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="Заголовок (EN)"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Заголовок (RU)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=255, verbose_name="Заголовок (KG)"),
                ),
                (
                    "short_description_en",
                    models.TextField(blank=True, verbose_name="Краткое описание (EN)"),
                ),
                (
                    "short_description_ru",
                    models.TextField(blank=True, verbose_name="Краткое описание (RU)"),
                ),
                (
                    "short_description_kg",
                    models.TextField(blank=True, verbose_name="Краткое описание (KG)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Полное описание (EN)"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, verbose_name="Полное описание (RU)"),
                ),
                (
                    "description_kg",
                    models.TextField(blank=True, verbose_name="Полное описание (KG)"),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Автор"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="publications/pdfs/",
                        verbose_name="PDF файл",
                    ),
                ),
                (
                    "published_at",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="presscentre.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
