# Generated by Django 5.2.8 on 2025-12-14 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presscentre", "0007_publication"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, verbose_name="Название (EN)"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=255, verbose_name="Название (RU)"),
                ),
                (
                    "title_kg",
                    models.CharField(max_length=255, verbose_name="Название (KG)"),
                ),
            ],
            options={
                "verbose_name": "Категория публикации",
                "verbose_name_plural": "Категории публикаций",
                "ordering": ["title_ru"],
            },
        ),
        migrations.AlterField(
            model_name="publication",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publications",
                to="presscentre.publicationcategory",
                verbose_name="Категория",
            ),
        ),
    ]
