# Generated by Django 6.0 on 2025-12-27 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0008_publicationcategory_alter_publication_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='PublicationCategory',
        ),
    ]
