# Generated by Django 6.0 on 2025-12-27 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0010_auto_20251227_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Изображение для галереи новости', upload_to='news/gallery/', verbose_name='Изображение')),
                ('alt_text_en', models.CharField(blank=True, max_length=255, verbose_name='Alt текст (EN)')),
                ('alt_text_ru', models.CharField(blank=True, max_length=255, verbose_name='Alt текст (RU)')),
                ('alt_text_kg', models.CharField(blank=True, max_length=255, verbose_name='Alt текст (KG)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения в галерее', verbose_name='Порядок')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='presscentre.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Изображение галереи новости',
                'verbose_name_plural': 'Изображения галереи новостей',
                'ordering': ['order', 'id'],
            },
        ),
    ]
