# Generated by Django 6.0 on 2025-12-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0011_newsimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimage',
            name='alt_text_en',
        ),
        migrations.RemoveField(
            model_name='newsimage',
            name='alt_text_kg',
        ),
        migrations.RemoveField(
            model_name='newsimage',
            name='alt_text_ru',
        ),
    ]
