# Generated by Django 6.0 on 2025-12-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presscentre', '0012_remove_newsimage_alt_text_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='is_banner',
        ),
    ]
