# Generated by Django 5.2.11 on 2026-02-20 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentCouncilMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name_ru', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(max_length=255)),
                ('full_name_kg', models.CharField(max_length=255)),
                ('role_ru', models.CharField(max_length=255)),
                ('role_en', models.CharField(max_length=255)),
                ('role_kg', models.CharField(max_length=255)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_kg', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='council/')),
                ('is_council_member', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ScientificTechnicalCouncilMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name_ru', models.CharField(max_length=255)),
                ('full_name_en', models.CharField(max_length=255)),
                ('full_name_kg', models.CharField(max_length=255)),
                ('role_ru', models.CharField(max_length=255)),
                ('role_en', models.CharField(max_length=255)),
                ('role_kg', models.CharField(max_length=255)),
                ('is_head', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
