# Generated by Django 5.2.11 on 2026-02-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developmentcouncilmember',
            options={'ordering': ['order'], 'verbose_name': 'Член Совета по развитию', 'verbose_name_plural': 'Члены Совета по развитию'},
        ),
        migrations.AlterModelOptions(
            name='scientifictechnicalcouncilmember',
            options={'ordering': ['order'], 'verbose_name': 'Член Научно-Технического Совета', 'verbose_name_plural': 'Члены Научно-Технического Совета'},
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (eng)'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='description_kg',
            field=models.TextField(blank=True, verbose_name='Описание (кг)'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (рус)'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full Name (eng)'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='full_name_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО (кг)'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='full_name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО (рус)'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='is_council_member',
            field=models.BooleanField(default=False, verbose_name='Состав совета'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='council/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='role_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Role (eng)'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='role_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность (кг)'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='role_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность (рус)'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='scientifictechnicalcouncilmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='scientifictechnicalcouncilmember',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full Name (eng)'),
        ),
        migrations.AlterField(
            model_name='scientifictechnicalcouncilmember',
            name='full_name_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО (кг)'),
        ),
        migrations.AlterField(
            model_name='scientifictechnicalcouncilmember',
            name='full_name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО (рус)'),
        ),
        migrations.AlterField(
            model_name='scientifictechnicalcouncilmember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='scientifictechnicalcouncilmember',
            name='is_head',
            field=models.BooleanField(default=False, verbose_name='Руководство совета'),
        ),
        migrations.AlterField(
            model_name='scientifictechnicalcouncilmember',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='scientifictechnicalcouncilmember',
            name='role_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Role (eng)'),
        ),
        migrations.AlterField(
            model_name='scientifictechnicalcouncilmember',
            name='role_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кызмат орду(кг)'),
        ),
        migrations.AlterField(
            model_name='scientifictechnicalcouncilmember',
            name='role_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность (рус)'),
        ),
        migrations.AlterField(
            model_name='scientifictechnicalcouncilmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
