# Generated by Django 5.2.11 on 2026-02-23 04:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_developmentcouncilmember_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (eng)'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='description_kg',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Суроттомо (кр)'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание (рус)'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='full_name_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО (кр)'),
        ),
        migrations.AlterField(
            model_name='developmentcouncilmember',
            name='role_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кызмат орду (кр)'),
        ),
        migrations.AlterField(
            model_name='scientifictechnicalcouncilmember',
            name='full_name_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО (кр)'),
        ),
        migrations.AlterField(
            model_name='scientifictechnicalcouncilmember',
            name='role_kg',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кызмат орду(кр)'),
        ),
    ]
