# Generated by Django 6.0.4 on 2026-06-10 11:19

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_developmentcouncilmember_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='Slug')),
                ('title_ru', models.CharField(blank=True, max_length=255, verbose_name='Title (RU)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (EN)')),
                ('title_kg', models.CharField(blank=True, max_length=255, verbose_name='Title (KG)')),
                ('subtitle_ru', models.TextField(blank=True, verbose_name='Subtitle (RU)')),
                ('subtitle_en', models.TextField(blank=True, verbose_name='Subtitle (EN)')),
                ('subtitle_kg', models.TextField(blank=True, verbose_name='Subtitle (KG)')),
                ('body_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Body (RU)')),
                ('body_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Body (EN)')),
                ('body_kg', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Body (KG)')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Structured data')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Page content',
                'verbose_name_plural': 'Page contents',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PageMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(blank=True, max_length=120, verbose_name='Key')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='image', max_length=20, verbose_name='Type')),
                ('file', models.FileField(blank=True, null=True, upload_to='pages/', verbose_name='File')),
                ('external_url', models.URLField(blank=True, verbose_name='External URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='about.pagecontent')),
            ],
            options={
                'verbose_name': 'Page media',
                'verbose_name_plural': 'Page media',
                'ordering': ['order', 'id'],
            },
        ),
    ]
