# Generated by Django 6.0.4 on 2026-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_seed_founder_message_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Frontend path'),
        ),
    ]
